#index:
#    path: /
#    controller: App\Controller\DefaultController::index


# routes for client
#client_dashboard:
 #   path: /home
  #  controller: App\Controller\HomeController::index

# routes for admin
#admin_dashboard:
 #   path: /dashboard/users
 #   controller: App\Controller\UserController::Show

# routes for coach
#coach_dashboard:
 #   path: /coach/{id}/dashboard
  #  controller: App\Controller\CoachController::dashboard
