<?php

namespace ContainerR57H4SB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A7iS_ImService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A7iS.Im' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A7iS.Im'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'student' => ['privates', '.errored..service_locator.A7iS.Im.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.A7iS.Im": it references class "App\\Entity\\User" but no such service exists.'],
            'studentRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'student' => 'App\\Entity\\User',
            'studentRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
