<?php

namespace ContainerR57H4SB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSmsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.zKArbO8.Twilio\TwiML\Voice\Sms' shared service.
     *
     * @return \Twilio\TwiML\Voice\Sms
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.zKArbO8": it references class "Twilio\\TwiML\\Voice\\Sms" but no such service exists.');
    }
}
