<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHoZtUUk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHoZtUUk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHoZtUUk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHoZtUUk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHoZtUUk\App_KernelDevDebugContainer([
    'container.build_hash' => 'HoZtUUk',
    'container.build_id' => '056a01bc',
    'container.build_time' => 1682982054,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHoZtUUk');
