<?php

namespace ContainerCx6lvOm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReductionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.DQANm3w.App\Entity\Reduction' shared service.
     *
     * @return \App\Entity\Reduction
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.DQANm3w": it references class "App\\Entity\\Reduction" but no such service exists.');
    }
}
