<?php

namespace ContainerFRAyIBB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q5BFAb3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.q5BFAb3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.q5BFAb3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'livreur' => ['privates', '.errored..service_locator.q5BFAb3.App\\Entity\\Livreur', NULL, 'Cannot autowire service ".service_locator.q5BFAb3": it references class "App\\Entity\\Livreur" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'livreur' => 'App\\Entity\\Livreur',
        ]);
    }
}
