<?php

namespace ContainerFRAyIBB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QmNakCrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.QmNakCr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QmNakCr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'livraison' => ['privates', '.errored..service_locator.QmNakCr.App\\Entity\\Livraison', NULL, 'Cannot autowire service ".service_locator.QmNakCr": it references class "App\\Entity\\Livraison" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'livraison' => 'App\\Entity\\Livraison',
        ]);
    }
}
