<?php

namespace ContainerFRAyIBB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KDQtnBsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kDQtnBs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kDQtnBs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'livreur' => ['privates', '.errored..service_locator.kDQtnBs.App\\Entity\\Livreur', NULL, 'Cannot autowire service ".service_locator.kDQtnBs": it references class "App\\Entity\\Livreur" but no such service exists.'],
        ], [
            'livreur' => 'App\\Entity\\Livreur',
        ]);
    }
}
