<?php

namespace ContainerFRAyIBB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZFdPxPfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZFdPxPf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZFdPxPf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reductionRepository' => ['privates', 'App\\Repository\\ReductionRepository', 'getReductionRepositoryService', true],
        ], [
            'reductionRepository' => 'App\\Repository\\ReductionRepository',
        ]);
    }
}
