<?php

namespace ContainerFRAyIBB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IgerYitService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.IgerYit' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IgerYit'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'LivraisonRepository' => ['privates', 'App\\Repository\\LivraisonRepository', 'getLivraisonRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'LivraisonRepository' => 'App\\Repository\\LivraisonRepository',
            'entityManager' => '?',
        ]);
    }
}
