<?php

namespace ContainerFRAyIBB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZKArbO8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zKArbO8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zKArbO8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'reclamation' => ['privates', '.errored..service_locator.zKArbO8.App\\Entity\\Reclamation', NULL, 'Cannot autowire service ".service_locator.zKArbO8": it references class "App\\Entity\\Reclamation" but no such service exists.'],
            'sms' => ['privates', '.errored..service_locator.zKArbO8.Twilio\\TwiML\\Voice\\Sms', NULL, 'Cannot autowire service ".service_locator.zKArbO8": it references class "Twilio\\TwiML\\Voice\\Sms" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'reclamation' => 'App\\Entity\\Reclamation',
            'sms' => 'Twilio\\TwiML\\Voice\\Sms',
        ]);
    }
}
