<?php

namespace ContainerFRAyIBB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEchangeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6RhudBK.App\Entity\Echange' shared service.
     *
     * @return \App\Entity\Echange
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.6RhudBK": it references class "App\\Entity\\Echange" but no such service exists.');
    }
}
