<?php

namespace ContainerHoZtUUk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CQp3mJyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cQp3mJy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cQp3mJy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'clubRepository' => ['privates', 'App\\Repository\\ServiceRepository', 'getServiceRepositoryService', true],
        ], [
            'clubRepository' => 'App\\Repository\\ServiceRepository',
        ]);
    }
}
