<?php

namespace ContainerHoZtUUk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GYS1EYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gYS1E_Y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gYS1E_Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'echange' => ['privates', '.errored..service_locator.gYS1E_Y.App\\Entity\\Echange', NULL, 'Cannot autowire service ".service_locator.gYS1E_Y": it references class "App\\Entity\\Echange" but no such service exists.'],
        ], [
            'echange' => 'App\\Entity\\Echange',
        ]);
    }
}
