<?php

namespace ContainerHoZtUUk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__KZLQmcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..KZLQmc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..KZLQmc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ServiceRepository' => ['privates', 'App\\Repository\\ServiceRepository', 'getServiceRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'ServiceRepository' => 'App\\Repository\\ServiceRepository',
            'entityManager' => '?',
        ]);
    }
}
