<?php

namespace ContainerHoZtUUk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YZMPeOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YZM_peO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YZM_peO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'livraison' => ['privates', '.errored..service_locator.YZM_peO.App\\Entity\\Livraison', NULL, 'Cannot autowire service ".service_locator.YZM_peO": it references class "App\\Entity\\Livraison" but no such service exists.'],
        ], [
            'livraison' => 'App\\Entity\\Livraison',
        ]);
    }
}
