<?php

namespace ContainerHoZtUUk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MMVhHVgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MMVhHVg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MMVhHVg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ReclamationRepository' => ['privates', 'App\\Repository\\ReclamationRepository', 'getReclamationRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'ReclamationRepository' => 'App\\Repository\\ReclamationRepository',
            'entityManager' => '?',
        ]);
    }
}
