<?php

namespace ContainerHoZtUUk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YDVP6QGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YDVP6QG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YDVP6QG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'v' => ['privates', '.errored.FasIbO2', NULL, 'Cannot determine controller argument for "App\\Controller\\UserController::fonc()": the $v argument is type-hinted with the non-existent class or interface: "App\\Controller\\VoitureRepository". Did you forget to add a use statement?'],
        ], [
            'paginator' => '?',
            'v' => '?',
        ]);
    }
}
