<?php

namespace ContainerHoZtUUk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RaFmU79Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RaFmU79' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RaFmU79'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reduction' => ['privates', '.errored..service_locator.RaFmU79.App\\Entity\\Reduction', NULL, 'Cannot autowire service ".service_locator.RaFmU79": it references class "App\\Entity\\Reduction" but no such service exists.'],
            'reductionRepository' => ['privates', 'App\\Repository\\ReductionRepository', 'getReductionRepositoryService', true],
        ], [
            'reduction' => 'App\\Entity\\Reduction',
            'reductionRepository' => 'App\\Repository\\ReductionRepository',
        ]);
    }
}
