<?php

namespace ContainerHoZtUUk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NMqVqAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nMqVq_a' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nMqVq_a'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'EchangeRepository' => ['privates', 'App\\Repository\\EchangeRepository', 'getEchangeRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'EchangeRepository' => 'App\\Repository\\EchangeRepository',
            'entityManager' => '?',
        ]);
    }
}
