<?php

namespace ContainerHoZtUUk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLivreurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.S8mtfrM.App\Entity\Livreur' shared service.
     *
     * @return \App\Entity\Livreur
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.S8mtfrM": it references class "App\\Entity\\Livreur" but no such service exists.');
    }
}
